spring:
  application:
    name: 'user-service-api'
  cloud:
    config:
      name: 'user-service-api'
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}